//
//  Constants.swift
//  threadsApp
//
//  Created by Gururaj Baskaran on 2/2/18.
//  Copyright © 2018 Gururaj Baskaran. All rights reserved.
//

import Foundation

final class Constants {
    
    private init(){}
    
    static let sharedInstance = Constants()
    
    
    
    let _threads = "threads"
    let _emptyString = ""
    let _id = "id"
    let _visibility = "visibility"
    let _createdDate = "createdDate"
    let _Thread_ = "Thread_"
    let _createdBy = "createdBy"
    let _profileImage = "profileImage"
    let _about = "about"
    let _title = "title"
    let _mediaCore = "mediaCore"
    let _User = "User"
    let _username = "username"
    let _fullname = "fullname"
    let _bio = "bio"
    let _Following = "Following"
    let _Followers = "Followers"
    let _Photos = "Photos"
    let _Photo = "Photo"
    let _Audio = "Audio"
    let _Film = "Film"
    let _Threads = "Threads"
    let _Instance = "Instance"
    let _Instances = "Instances"
    let _instances = "instances"
    let _AudioItem = "AudioItem"
    let _Moderating = "Moderating"
    let _creator = "creator"
    let _moderators = "moderators"
    let _body = "body"
    let _photos = "photos"
    let _videos = "videos"
    let _audio = "audio"
    let _parentKey = "parentKey"
    let _parent = "parent"
    let _TextFieldTVC = "TextFieldTVC"
    let _lowQuality = "lowQuality"
    let _mediumQuality = "mediumQuality"
    let _highQuality = "highQuality"
    let _TextViewTVC = "TextViewTVC"
    let _TypicalTVCell = "TypicalTVCell"
    let _TextTVC = "TextTVC"
    let _Bio = "Bio"
    let _Current = "Current"
    let _Follow = "Follow"
    let _Pending = "Pending"
    let _Requested = "Requested"
    let _UserListVC = "UserListVC"
    let _ThreadTVC = "ThreadTVC"
    let _UserTVC = "UserTVC"
    let _Loading = "Loading"
    let _EditUserVC = "EditUserVC"
    let _Edit = "Edit"
    let _ProfileVC = "ProfileVC"
    let _ThreadProfileVC = "ThreadProfileVC"
    let _SharedThreads = "SharedThreads"
    let _SharedInstances = "SharedInstances"
    let _BookmarkedThreads = "BookmarkedThreads"
    let _BookmarkedInstances = "BookmarkedInstances"
    let _Shared = "Shared"
    let _Share = "Share"
    let _Bookmark = "Bookmark"
    let _Bookmarked = "Bookmarked"
    let _SwitchTVC = "SwitchTVC"
    let _EditThreadVC = "EditThreadVC"
    let _Moderators = "Moderators"
    let _EditModeratorsList = "EditModeratorsList"
    let _Remove = "Remove"
    let _Add = "Add"
    let _Error = "Error"
    let _SelectModeratorsList = "SelectModeratorsList"
    let _InstanceTVC = "InstanceTVC"
    let _ThreadListVC = "ThreadListVC"
    let _InstanceProfileVC = "InstanceProfileVC"
    let _Back = "Back"
    let _PhotoCVC = "PhotoCVC"
    let _FilmCVC = "FilmCVC"
    let _AudioCVC = "AudioCVC"
    let _children = "children"
    let _Done = "Done"
    let _CreateThreadVC = "CreateThreadVC"
    let _Visibility = "Visibility"
    let _Yes = "Yes"
    let _No = "No"
    let _threadProfileImage = "threadProfileImage"
    let _Cancel = "Cancel"
    let _profileImageURL = "profileImageURL"
    let _Images = "Images"
    let _Failed = "Failed"
    let _Try_Again = "Try Again"
    let _UIImagePickerControllerOriginalImage = "UIImagePickerControllerOriginalImage"
    let _Username = "Username"
    let _Full_name = "Full name"
    let _Warning = "Warning"
    let _Edit_Profile_Image = "Edit Profile Image"
    let _Change = "Change"
    let _CreateThreadVC_Part_2 = "CreateThreadVC_Part_2"
    let _Okay = "Okay"
    let _CreateInstanceStepOneVC = "CreateInstanceStepOneVC"
    let _CreateInstanceStepTwoVC = "CreateInstanceStepTwoVC"
    let _TitleTVC = "TitleTVC"
    let _ButtonTVC = "ButtonTVC"
    let _Create_Media = "Create Media"
    let _Next = "Next"
    let _Videos = "Videos"
    let _Add_Media = "Add Media"
    let _AddPhotoCVC = "AddPhotoCVC"
    let _MediaListVC = "MediaListVC"
    let _Create_Instance = "Create Instance"
    let _images = "images"
    let _imageName = "imageName"
    let _About = "About"
    let _ImageTVC = "ImageTVC"
    let _MediaAboutVC = "MediaAboutVC"
    let _imageURL = "imageURL"
    let _Close = "Close"
    let _Sign_Out = "Sign Out"
    let _following = "following"
    let _UnFollow = "UnFollow"
    let _Cancel_Pending = "Cancel Pending"
    let _Accept_Pending = "Accept Pending"
    let _Stop_Following = "Stop Following"
    let _Edit_User = "Edit User"
    let _Save = "Save"
    let _Change_password = "Change password"
    let _Public = "Public"
    let _Create_Thread = "Create Thread"
    let _Blocked = "Blocked"
    let _isCurrent = "isCurrent"
    let _isPending = "isPending"
    let _isRequesting = "isRequesting"
    let _isFollowing = "isFollowing"
    let _Alert = "Alert"
    let _LoginVC = "LoginVC"
    let _Login = "Login"
    let _Invalid_User_Credentials = "Invalid User Credentials"
    let _Email = "Email"
    let _Password = "Password"
    let _Forgot_Password = "Forgot Password"
    let _Register = "Register"
    let _CreateUserVC = "CreateUserVC"
    let _launchUserIntoApp = "launchUserIntoApp"
    let _WelcomeVC = "WelcomeVC"
    let _Create = "Create"
    let _ProfileImageTVC = "ProfileImageTVC"
    let _ViewController = "ViewController"
    let _featureNotAvailMessage = "Feature not available right now."
    let _Withdraw = "Withdraw"
    let _Un_Follow = "Un Follow"
    let _InstanceImageCVC = "InstanceImageCVC"
    let _CollectionViewTVC = "CollectionViewTVC"
    let _bodyTitle = "bodyTitle"
    let _bodyText = "bodyText"
    let _Body = "Body"
    let _Bodies = "Bodies"
    let _InstanceEditVC = "InstanceEditVC"
    let _Private = "Private"
    let _Delete = "Delete"
    let _EditBodyVC = "EditBodyVC"
    let _Title = "Title"
    let _Edit_Mode = "Edit Mode"
    let _VisibilityBarButtonItem = "VisibilityBarButtonItem"
    let _AddBarButtonItem = "AddBarButtonItem"
    let _DeleteBarButtonItem = "DeleteBarButtonItem"
    let _EditBarButtonItem = "EditBarButtonItem"
    let _VisibilityStateButton = "VisibilityStateButton"
    let _NewInstanceVC = "NewInstanceVC"
    let _CreateMediaVC = "CreateMediaVC"
    let _InstanceCVC = "InstanceCVC"
    let _Video = "Video"
    
    let _SharedBodies = "SharedBodies"
    let _SharedPhotos = "SharedPhotos"
    let _SharedVideos = "SharedVideos"
    let _SharedAudio =  "SharedAudio"
    
    let _sharedThreads = "sharedThreads"
    let _sharedBodies = "sharedBodies"
    let _sharedPhotos = "sharedPhotos"
    let _sharedVideos = "sharedVideos"
    let _sharedAudio =  "sharedAudio"
    
    let _BookmarkedBodies = "BookmarkedBodies"
    let _BookmarkedPhotos = "BookmarkedPhotos"
    let _BookmarkedVideos = "BookmarkedVideos"
    let _BookmarkedAudio =  "BookmarkedAudio"
    
    let _Bookmarked_Bodies = "Bookmarked Bodies"
    let _Bookmarked_Photos = "Bookmarked Photos"
    let _Bookmarked_Videos = "Bookmarked Videos"
    let _Bookmarked_Audio =  "Bookmarked Audio"
    let _Bookmarked_Threads = "Bookmarked Threads"
    
    let _bookmarkedThreads = "bookmarkedThreads"
    let _bookmarkedBodies = "bookmarkedBodies"
    let _bookmarkedPhotos = "bookmarkedPhotos"
    let _bookmarkedVideos = "bookmarkedVideos"
    let _bookmarkedAudio =  "bookmarkedAudio"
    
    let _createdThreads = "createdThreads"
    let _createdBodies = "createdBodies"
    let _createdPhotos = "createdPhotos"
    let _createdVideos = "createdVideos"
    let _createdAudio =  "createdAudio"
    
    let _CreatedThreads = "CreatedThreads"
    let _CreatedBodies = "CreatedBodies"
    let _CreatedPhotos = "CreatedPhotos"
    let _CreatedVideos = "CreatedVideos"
    let _CreatedAudio =  "CreatedAudio"
    
    
    let _Journal = "Journal"
    let _text = "text"
    
    let _More = "More"
    
    let _Report = "Report"
    let _Block = "Block"
    
    let _NotepadVC = "NotepadVC"
    
    let _FeedItem = "FeedItem"
    let _JournalItem = "JournalItem"
    
    let _message = "message"
    
    let _targetThread = "targetThread"
    let _targetBody = "targetBody"
    let _targetPhoto = "targetPhoto"
    let _targetVideo = "targetVideo"
    let _targetAudio = "targetAudio"
    let _targetUser = "targetUser"
    
    let _target = "target"
    
    let _Feed = "Feed"
    let _You = "You"
    
    let _FeedThreadCVC = "FeedThreadCVC"
   
    let _ifId = "id = %@"
    
    let _pending = "pending"
    let _followers = "followers"
    let _requested = "requested"
    
    let _media = "media"
    
    let _feed = "feed"
    let _journal = "journal"
    let _borrowedBy = "borrowedBy"
    
    let _ThreadFeedTVC = "ThreadFeedTVC"
    let _FeedBodyTVC = "FeedBodyTVC"
    let _FeedPhotoTVC = "FeedPhotoTVC"
    
    let _Load_More = "Load More"
}
